@echo off
echo [1/3] מתקין רכיבים נחוצים (בפעם הראשונה זה עשוי לקחת דקה)...
pip install -r requirements.txt --quiet
echo [2/3] מפעיל את מנוע הבינה המלאכותית...
echo [3/3] פותח את ממשק הניהול בדפדפן...
start http://localhost:8000
python main.py
pause